"""Figures for the FAccT submission.

fig_dose_response: v2 deception rate by intensity in the rerun (baseline vs fixed
testbed, Wilson 95% CI), with the original matrix ComputerUse (E1a) raw DC curve.

Inputs:  results/rerun/by_intensity.csv (scripts/analyze_rerun.py)
         docs/paper/tables/T3_intensity.tex (scripts/corrected_tables.py), E1a raw column
Outputs: docs/paper/submission/figures/fig_dose_response.{pdf,tex}

    python scripts/make_figures.py
"""

from __future__ import annotations

import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import pandas as pd  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
RERUN = ROOT / "results" / "rerun"
T3 = ROOT / "docs" / "paper" / "tables" / "T3_intensity.tex"
OUT = ROOT / "docs" / "paper" / "submission" / "figures"

INTENSITIES = ["control", "subtle", "moderate", "aggressive"]
INK = "#1a1a1a"
MUTED = "#6b6b6b"


def original_e1a_raw() -> list[float]:
    """E1a raw DC rate per intensity, parsed from the generated T3 table."""
    text = T3.read_text(encoding="utf-8")
    rates = {}
    for i in INTENSITIES:
        m = re.search(rf"^E1a & {i} & (\d+)/(\d+) ", text, flags=re.M)
        if not m:
            raise SystemExit(f"E1a {i} not found in {T3}")
        rates[i] = int(m.group(1)) / int(m.group(2))
    return [100 * rates[i] for i in INTENSITIES]


def fig_dose_response() -> Path:
    bi = pd.read_csv(RERUN / "by_intensity.csv").set_index(["variant", "intensity"])
    x = list(range(len(INTENSITIES)))

    plt.rcParams.update({
        "font.family": "serif", "font.size": 9, "axes.labelsize": 9, "legend.fontsize": 8,
        "xtick.labelsize": 8.5, "ytick.labelsize": 8.5, "pdf.fonttype": 42,
        "axes.edgecolor": MUTED, "axes.labelcolor": INK, "xtick.color": MUTED, "ytick.color": MUTED,
    })
    fig, ax = plt.subplots(figsize=(5.0, 2.9))

    series = [
        ("baseline", "rerun, baseline testbed (Qwen3.8-27B, T=0.7)", INK, "o", "-", -0.06),
        ("fixed", "rerun, fixed testbed (Qwen3.8-27B, T=0.7)", INK, "s", "--", +0.06),
    ]
    for variant, label, color, marker, ls, dx in series:
        rows = [bi.loc[(variant, i)] for i in INTENSITIES]
        y = [100 * r.v2_deception_rate for r in rows]
        # Wilson bounds can sit a float epsilon past the point estimate at 0%.
        lo = [100 * max(r.v2_deception_rate - r.v2_ci_lo, 0.0) for r in rows]
        hi = [100 * max(r.v2_ci_hi - r.v2_deception_rate, 0.0) for r in rows]
        ax.errorbar([xi + dx for xi in x], y, yerr=[lo, hi], label=label, color=color,
                    marker=marker, markersize=5.5, markerfacecolor="white" if variant == "fixed" else color,
                    linestyle=ls, linewidth=1.4, capsize=2.5, elinewidth=0.9, zorder=3)

    ax.plot(x, original_e1a_raw(), label="original matrix (Llama-3.3-70B, T=0)", color=MUTED,
            marker="^", markersize=5.5, linestyle=":", linewidth=1.4, zorder=2)

    ax.set_xticks(x, INTENSITIES)
    ax.set_xlim(-0.3, len(x) - 0.7)
    ax.set_ylim(0, 45)
    ax.set_ylabel("deception rate (%)")
    ax.set_xlabel("intensity")
    ax.grid(axis="y", color="#d9d9d9", linewidth=0.6, zorder=0)
    ax.spines[["top", "right"]].set_visible(False)
    handles, labels = ax.get_legend_handles_labels()
    order = [labels.index(lb) for lb in [s[1] for s in series]] + [labels.index("original matrix (Llama-3.3-70B, T=0)")]
    ax.legend([handles[k] for k in order], [labels[k] for k in order],
              loc="upper left", frameon=False, handlelength=2.6)
    fig.tight_layout(pad=0.3)

    OUT.mkdir(parents=True, exist_ok=True)
    pdf = OUT / "fig_dose_response.pdf"
    fig.savefig(pdf)
    plt.close(fig)

    (OUT / "fig_dose_response.tex").write_text(
        "% Generated by scripts/make_figures.py -- caption is a placeholder for the author.\n"
        "\\begin{figure}[htbp]\n"
        "\\centering\n"
        "\\includegraphics[width=0.55\\linewidth]{figures/fig_dose_response.pdf}\n"
        "\\caption{Deception rate by intensity: rerun baseline vs fixed testbed (Wilson 95\\% CI) and original matrix.}\n"
        "\\label{fig:dose}\n"
        "\\end{figure}\n",
        encoding="utf-8", newline="\n",
    )
    return pdf


def main() -> None:
    for f in (fig_dose_response(),):
        print(f"wrote {f.relative_to(ROOT)} (+ .tex)")


if __name__ == "__main__":
    main()
