"""Rerun tables R1-R3 (booktabs) for the FAccT submission.

Reads results/rerun/{by_intensity,trend_summary,h1_cells,cells}.csv, written by
scripts/analyze_rerun.py, and writes docs/paper/submission/tables/R*.tex.
No database access. Re-run after analyze_rerun.py; do not edit the output by hand.

    python scripts/make_rerun_tables.py
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RERUN = ROOT / "results" / "rerun"
OUT = ROOT / "docs" / "paper" / "submission" / "tables"

INTENSITIES = ["control", "subtle", "moderate", "aggressive"]
VARIANTS = ["baseline", "fixed"]
H1_CELLS = [("drip_pricing", "aggressive"), ("saas_billing", "aggressive"),
            ("trick_question", "moderate"), ("trick_question", "aggressive")]
HEADER = "% Generated by scripts/make_rerun_tables.py from results/rerun/*.csv -- do not edit by hand.\n"


def tex(s: str) -> str:
    return s.replace("_", r"\_")


def pct(p: float) -> str:
    return f"{100 * p:.1f}"


def rate_ci(p: float, lo: float, hi: float) -> str:
    return f"{pct(p)}\\% [{pct(max(lo, 0.0))}, {pct(min(hi, 1.0))}]"


def write(name: str, body: str) -> Path:
    path = OUT / name
    path.write_text(HEADER + body, encoding="utf-8", newline="\n")
    return path


def r1() -> Path:
    bi = pd.read_csv(RERUN / "by_intensity.csv").set_index(["variant", "intensity"])
    ts = pd.read_csv(RERUN / "trend_summary.csv")
    ts = ts[(ts.scoring == "v2") & (~ts.exclude_flagged)].set_index("variant")

    rows = []
    for i in INTENSITIES:
        cells = [i]
        for v in VARIANTS:
            r = bi.loc[(v, i)]
            cells += [f"{int(r.v2_deceived)}/{int(r.v2_scored)}",
                      rate_ci(r.v2_deception_rate, r.v2_ci_lo, r.v2_ci_hi),
                      f"{pct(r.cell_mean_v2)}\\%"]
        rows.append(" & ".join(cells) + r" \\")
    sign = ["Sign test (cells, one-sided)"]
    mono = ["Pooled rates monotone"]
    for v in VARIANTS:
        t = ts.loc[v]
        sign.append(rf"\multicolumn{{3}}{{l}}{{{int(t.sign_pos)}+/{int(t.sign_neg)}$-$, $p={t.sign_p:.3f}$}}")
        mono.append(rf"\multicolumn{{3}}{{l}}{{{'yes' if t.monotone else 'no'}}}")

    body = rf"""\begin{{table}}[htbp]
\caption{{Rerun v2 deception rate by intensity, baseline vs fixed testbed (Wilson 95\% CI).}}
\label{{tab:r1}}
\centering
\small
\begin{{tabular}}{{lrlrrlr}}
\toprule
 & \multicolumn{{3}}{{c}}{{\textbf{{Baseline}}}} & \multicolumn{{3}}{{c}}{{\textbf{{Fixed}}}} \\
\cmidrule(lr){{2-4}}\cmidrule(lr){{5-7}}
\textbf{{Intensity}} & \textbf{{dec./n}} & \textbf{{rate [CI]}} & \textbf{{cell mean}} & \textbf{{dec./n}} & \textbf{{rate [CI]}} & \textbf{{cell mean}} \\
\midrule
{chr(10).join(rows)}
\midrule
{" & ".join(sign)} \\
{" & ".join(mono)} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    return write("R1_intensity.tex", body)


def r2() -> Path:
    h1 = pd.read_csv(RERUN / "h1_cells.csv").set_index(["pattern", "intensity", "variant"])
    rows = []
    for k, (p, i) in enumerate(H1_CELLS):
        for j, v in enumerate(VARIANTS):
            r = h1.loc[(p, i, v)]
            label = [tex(p), i] if j == 0 else ["", ""]
            counts = [str(int(r[c])) for c in ("EC", "DC", "DF", "RF", "NC")]
            rows.append(" & ".join(label + [v] + counts + [rate_ci(r.deception_rate, r.ci_lo, r.ci_hi)]) + r" \\")
        if k < len(H1_CELLS) - 1:
            rows.append(r"\addlinespace")
    body = rf"""\begin{{table}}[htbp]
\caption{{Formerly BREAKING cells in the rerun: v2 outcome counts and deception rate (Wilson 95\% CI).}}
\label{{tab:r2}}
\centering
\small
\begin{{tabular}}{{lllrrrrrl}}
\toprule
\textbf{{Pattern}} & \textbf{{Intensity}} & \textbf{{Variant}} & \textbf{{EC}} & \textbf{{DC}} & \textbf{{DF}} & \textbf{{RF}} & \textbf{{NC}} & \textbf{{Deception [CI]}} \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    return write("R2_h1_cells.tex", body)


def r3() -> Path:
    cells = pd.read_csv(RERUN / "cells.csv")
    fx = cells[cells.variant == "fixed"].set_index(["pattern", "intensity"])
    patterns = sorted(fx.index.get_level_values(0).unique())
    rows = []
    for p in patterns:
        vals = [f"{int(fx.loc[(p, i)].deceived)}/{int(fx.loc[(p, i)].scored)}" for i in INTENSITIES]
        rows.append(" & ".join([tex(p)] + vals) + r" \\")
    body = rf"""\begin{{table}}[htbp]
\caption{{Rerun, fixed testbed: v2 deceived/scored by pattern and intensity.}}
\label{{tab:r3}}
\centering
\small
\begin{{tabular}}{{lrrrr}}
\toprule
\textbf{{Pattern}} & \textbf{{control}} & \textbf{{subtle}} & \textbf{{moderate}} & \textbf{{aggressive}} \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    return write("R3_pattern_intensity.tex", body)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for f in (r1(), r2(), r3()):
        print(f"wrote {f.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
