"""Build the FAccT submission: drafts/*.md -> sections/*.tex -> main.pdf.

    python docs/paper/submission/build.py            # convert + compile
    python docs/paper/submission/build.py --no-pdf   # convert only
    python docs/paper/submission/build.py --watch    # rebuild whenever a draft changes

Only drafts/*.md is hand-edited. sections/*.tex is regenerated on every run.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
DRAFTS = HERE / "drafts"
SECTIONS = HERE / "sections"
MAIN = "main"

NBSP = "\u00a0"
PANDOC_FROM = "markdown-auto_identifiers-subscript-strikeout"
HEADER = "% Generated by build.py from drafts/{name}.md -- do not edit; edit the draft instead.\n"


def convert(md_path: Path) -> Path:
    name = md_path.stem
    text = md_path.read_text(encoding="utf-8")
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)  # author notes never reach the PDF

    # The first "# Title" becomes the numbered section with a stable label.
    section = ""
    m = re.search(r"^#[ \t]+(.+?)[ \t]*#*[ \t]*$", text, flags=re.M)
    if m:
        title = m.group(1).strip()
        section = f"\\section{{{title}}}\\label{{sec:{name}}}\n\n"
        text = text[: m.start()] + text[m.end():]

    # "Table~\ref{x}": pandoc would escape a bare ~, so carry it as a no-break
    # space and restore it afterwards (also inside raw TeX such as \cite[p.~3]{k}).
    text = re.sub(r"(?<=\S)~(?=\S)", NBSP, text)

    res = subprocess.run(
        ["pandoc", "-f", PANDOC_FROM, "-t", "latex", "--wrap=preserve"],
        input=text, capture_output=True, text=True, encoding="utf-8",
    )
    if res.returncode != 0:
        sys.exit(f"pandoc failed on {md_path.name}:\n{res.stderr}")
    body = res.stdout.replace(NBSP, "~")
    if res.stderr.strip():
        print(f"  pandoc ({md_path.name}): {res.stderr.strip()}")

    out = SECTIONS / f"{name}.tex"
    out.write_text(HEADER.format(name=name) + section + body, encoding="utf-8", newline="\n")
    return out


def convert_all() -> None:
    SECTIONS.mkdir(exist_ok=True)
    drafts = sorted(DRAFTS.glob("*.md"))
    for md in drafts:
        convert(md)
    print(f"converted {len(drafts)} drafts -> sections/")


def run(cmd: list[str]) -> int:
    return subprocess.run(cmd, cwd=HERE, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL).returncode


def compile_pdf() -> None:
    pdflatex = ["pdflatex", "-interaction=nonstopmode", "-file-line-error", f"{MAIN}.tex"]
    used = None
    if shutil.which("latexmk"):
        rc = run(["latexmk", "-pdf", "-interaction=nonstopmode", "-file-line-error", f"{MAIN}.tex"])
        if rc == 0:
            used = "latexmk"
        else:
            print(f"latexmk exited {rc} (missing Perl or a LaTeX error); falling back to pdflatex/bibtex")
    if used is None:
        run(pdflatex)
        aux = (HERE / f"{MAIN}.aux").read_text(encoding="utf-8", errors="replace") if (HERE / f"{MAIN}.aux").exists() else ""
        if "\\citation{" in aux:
            run(["bibtex", MAIN])
        else:
            (HERE / f"{MAIN}.bbl").unlink(missing_ok=True)  # no citations yet: skip the empty bibliography
        run(pdflatex)
        run(pdflatex)
        used = "pdflatex -> bibtex -> pdflatex x2"
    report(used)


def page_of(aux: str, label: str) -> str | None:
    m = re.search(r"\\newlabel\{" + re.escape(label) + r"\}\{\{[^{}]*\}\{([^{}]*)\}", aux)
    return m.group(1) if m else None


def report(used: str) -> None:
    log_path, aux_path = HERE / f"{MAIN}.log", HERE / f"{MAIN}.aux"
    log = log_path.read_text(encoding="utf-8", errors="replace") if log_path.exists() else ""
    aux = aux_path.read_text(encoding="utf-8", errors="replace") if aux_path.exists() else ""
    print(f"compiled with: {used}")

    errors = re.findall(r"^\S+:\d+: .+$|^! .+$", log, flags=re.M)
    for e in dict.fromkeys(errors):
        print(f"  LaTeX error: {e}")
    cites = sorted(set(re.findall(r"Citation `([^']+)' on page", log)))
    refs = sorted(set(re.findall(r"Reference `([^']+)' on page", log)))
    print(f"undefined citations ({len(cites)}): {', '.join(cites) or 'none'}")
    print(f"undefined references ({len(refs)}): {', '.join(refs) or 'none'}")

    total = re.search(r"Output written on \S+ \((\d+) pages?", log)
    body_end = page_of(aux, "body-end")
    print(f"pages through Conclusion (counted, limit 14): {body_end or 'unknown'}")
    print(f"total pages: {total.group(1) if total else 'unknown (no PDF?)'}")


def watch() -> None:
    def stamp() -> dict[Path, float]:
        files = list(DRAFTS.glob("*.md")) + list((HERE / "tables").glob("*.tex")) + list((HERE / "figures").glob("*"))
        return {p: p.stat().st_mtime for p in files}

    seen = stamp()
    print("watching drafts/, tables/, figures/ (Ctrl+C to stop)")
    while True:
        time.sleep(1)
        now = stamp()
        if now != seen:
            seen = now
            print(time.strftime("\n[%H:%M:%S] change detected"))
            convert_all()
            if not ARGS.no_pdf:
                compile_pdf()


def main() -> None:
    global ARGS
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-pdf", action="store_true", help="convert drafts only, do not compile")
    ap.add_argument("--watch", action="store_true", help="rebuild whenever a draft, table or figure changes")
    ARGS = ap.parse_args()
    convert_all()
    if not ARGS.no_pdf:
        compile_pdf()
    if ARGS.watch:
        try:
            watch()
        except KeyboardInterrupt:
            pass


ARGS: argparse.Namespace

if __name__ == "__main__":
    main()
